/* based on hal_interrupts_141009_1100.xls */

#ifndef __HAL_IRQID_INTERNAL_DPM_H
#define __HAL_IRQID_INTERNAL_DPM_H

typedef enum
{
  IRQID_INTERNAL_DPM_CRYPT = 9,
  IRQID_INTERNAL_DPM_TRIGGER_LT1 = 8,
  IRQID_INTERNAL_DPM_TRIGGER_LT0 = 7,
  IRQID_INTERNAL_DPM_GPIO15_0 = 6,
  IRQID_INTERNAL_DPM_WATCHDOG = 5,
  IRQID_INTERNAL_DPM_ARM_TIMER_SYSTIME_S = 4,
  IRQID_INTERNAL_DPM_ARM_TIMER = 3,
  IRQID_INTERNAL_DPM_IDPM_FIRMWARE = 2,
  IRQID_INTERNAL_DPM_IDPM_SW = 0
} IRQID_INTERNAL_DPM_E;
#endif
