/* auto generated by GEN_VIC_COLLECT, do not edit! */
/* from file: '/home/netx/doc/netXtiny/irq/netxtiny_interrupts_151215_1300.xls' */
/* time: Tue Dec 15 15:36:58 2015 */
/* user: buchhorn */

#ifndef __HW_IRQID_INTERNAL_DPM_H
#define __HW_IRQID_INTERNAL_DPM_H

typedef enum
{
  IRQID_INTERNAL_DPM_IDPM_COM_FIRMWARE = 2,
  IRQID_INTERNAL_DPM_IDPM_COM_SW = 0
} IRQID_INTERNAL_DPM_E;
#endif
