#ifndef __HAL_PHY_H
#define __HAL_PHY_H

/* IEEE register set */
#define ADR_PHYREG_BASIC_CONTROL                   0
#define ADR_PHYREG_BASIC_STATUS                    1
#define ADR_PHYREG_PHY_IDENTIFIER1                 2
#define ADR_PHYREG_PHY_IDENTIFIER2                 3
#define ADR_PHYREG_AUTONEG_ADV                     4
#define ADR_PHYREG_AUTONEG_LP_ABILITY              5
#define ADR_PHYREG_AUTONEG_EXPANSION               6
#define ADR_PHYREG_NEXT_PAGE_TRANSMIT              7

/* bit fields register 0 (BASIC CONTROL) */
#define MSK_PHYREG_BASIC_CONTROL_COLLISION_TEST    0x0080
#define MSK_PHYREG_BASIC_CONTROL_DUPLEX_MODE       0x0100
#define MSK_PHYREG_BASIC_CONTROL_RESTART_AUTONEG   0x0200
#define MSK_PHYREG_BASIC_CONTROL_ISOLATE           0x0400
#define MSK_PHYREG_BASIC_CONTROL_POWER_DOWN        0x0800
#define MSK_PHYREG_BASIC_CONTROL_AUTONEG_ENABLE    0x1000
#define MSK_PHYREG_BASIC_CONTROL_SPEED_SELECT      0x2000
#define MSK_PHYREG_BASIC_CONTROL_LOOPBACK          0x4000
#define MSK_PHYREG_BASIC_CONTROL_RESET             0x8000

/* bit fields register 1 (BASIC STATUS) */
#define MSK_PHYREG_BASIC_STATUS_EXTENDED_CAPS      0x0001
#define MSK_PHYREG_BASIC_STATUS_JABBER_DETECT      0x0002
#define MSK_PHYREG_BASIC_STATUS_LINK_STATUS        0x0004
#define MSK_PHYREG_BASIC_STATUS_AUTONEG_ABILITY    0x0008
#define MSK_PHYREG_BASIC_STATUS_REMOTE_FAULT       0x0010
#define MSK_PHYREG_BASIC_STATUS_AUTONEG_COMPLETE   0x0020
#define MSK_PHYREG_BASIC_STATUS_10BT_HD            0x0800
#define MSK_PHYREG_BASIC_STATUS_10BT_FD            0x1000
#define MSK_PHYREG_BASIC_STATUS_100BT_HD           0x2000
#define MSK_PHYREG_BASIC_STATUS_100BT_FD           0x4000
#define MSK_PHYREG_BASIC_STATUS_100BT4             0x8000

/* bit fields register 3 (PHY_IDENTIFIER2) */
#define SRT_PHYREG_PHY_IDENTIFIER2_REVISION        0
#define MSK_PHYREG_PHY_IDENTIFIER2_REVISION        0x000f
#define SRT_PHYREG_PHY_IDENTIFIER2_MODEL           4
#define MSK_PHYREG_PHY_IDENTIFIER2_MODEL           0x03f0
#define SRT_PHYREG_PHY_IDENTIFIER2_ID_HI           10
#define MSK_PHYREG_PHY_IDENTIFIER2_ID_HI           0xfc00

/* bit fields register 4 (AUTONEG_ADV) */
#define SRT_PHYREG_AUTONEG_ADV_SELECTOR            0
#define MSK_PHYREG_AUTONEG_ADV_SELECTOR            0x001f
#define SRT_PHYREG_AUTONEG_ADV_10BT                5
#define MSK_PHYREG_AUTONEG_ADV_10BT                0x0020
#define SRT_PHYREG_AUTONEG_ADV_10BT_FD             6
#define MSK_PHYREG_AUTONEG_ADV_10BT_FD             0x0040
#define SRT_PHYREG_AUTONEG_ADV_100BT               7
#define MSK_PHYREG_AUTONEG_ADV_100BT               0x0080
#define SRT_PHYREG_AUTONEG_ADV_100BT_FD            8
#define MSK_PHYREG_AUTONEG_ADV_100BT_FD            0x0100
#define SRT_PHYREG_AUTONEG_ADV_100BT4              9
#define MSK_PHYREG_AUTONEG_ADV_100BT4              0x0200
#define SRT_PHYREG_AUTONEG_ADV_PAUSE               10
#define MSK_PHYREG_AUTONEG_ADV_PAUSE               0x0c00
#define SRT_PHYREG_AUTONEG_ADV_REMOTE_FAULT        13
#define MSK_PHYREG_AUTONEG_ADV_REMOTE_FAULT        0x2000
#define SRT_PHYREG_AUTONEG_ADV_NEXT_PAGE           15
#define MSK_PHYREG_AUTONEG_ADV_NEXT_PAGE           0x8000

/* bit fields register 5 (AUTONEG_LP_ABILITY) */
#define SRT_PHYREG_AUTONEG_LP_ABILITY_SELECTOR     0
#define MSK_PHYREG_AUTONEG_LP_ABILITY_SELECTOR     0x001f
#define SRT_PHYREG_AUTONEG_LP_ABILITY_10BT         5
#define MSK_PHYREG_AUTONEG_LP_ABILITY_10BT         0x0020
#define SRT_PHYREG_AUTONEG_LP_ABILITY_10BT_FD      6
#define MSK_PHYREG_AUTONEG_LP_ABILITY_10BT_FD      0x0040
#define SRT_PHYREG_AUTONEG_LP_ABILITY_100BT        7
#define MSK_PHYREG_AUTONEG_LP_ABILITY_100BT        0x0080
#define SRT_PHYREG_AUTONEG_LP_ABILITY_100BT_FD     8
#define MSK_PHYREG_AUTONEG_LP_ABILITY_100BT_FD     0x0100
#define SRT_PHYREG_AUTONEG_LP_ABILITY_100BT4       9
#define MSK_PHYREG_AUTONEG_LP_ABILITY_100BT4       0x0200
#define SRT_PHYREG_AUTONEG_LP_ABILITY_PAUSE        10
#define MSK_PHYREG_AUTONEG_LP_ABILITY_PAUSE        0x0c00
#define SRT_PHYREG_AUTONEG_LP_ABILITY_REMOTE_FAULT 13
#define MSK_PHYREG_AUTONEG_LP_ABILITY_REMOTE_FAULT 0x2000
#define SRT_PHYREG_AUTONEG_LP_ABILITY_ACKNOWLEDGE  14
#define MSK_PHYREG_AUTONEG_LP_ABILITY_ACKNOWLEDGE  0x4000
#define SRT_PHYREG_AUTONEG_LP_ABILITY_NEXT_PAGE    15
#define MSK_PHYREG_AUTONEG_LP_ABILITY_NEXT_PAGE    0x8000

/* bit fields register 6 (AUTONEG_EX) */
#define SRT_PHYREG_AUTONEG_EXPANSION_LP_AUTONEG_ABLE   0
#define MSK_PHYREG_AUTONEG_EXPANSION_LP_AUTONEG_ABLE   0x0001
#define SRT_PHYREG_AUTONEG_EXPANSION_PAGE_RECEIVED     1
#define MSK_PHYREG_AUTONEG_EXPANSION_PAGE_RECEIVED     0x0002
#define SRT_PHYREG_AUTONEG_EXPANSION_NEXT_PAGE_ABLE    2
#define MSK_PHYREG_AUTONEG_EXPANSION_NETX_PAGE_ABLE    0x0004
#define SRT_PHYREG_AUTONEG_EXPANSION_LP_NEXT_PAGE_ABLE 3
#define MSK_PHYREG_AUTONEG_EXPANSION_LP_NETX_PAGE_ABLE 0x0008
#define SRT_PHYREG_AUTONEG_EXPANSION_PAR_DETECT_FAULT  4
#define MSK_PHYREG_AUTONEG_EXPANSION_PAR_DETECT_FAULT  0x0010

/* bit fields register 7 (NEXT_PAGE_TRANSMIT) */
#define SRT_PHYREG_NEXT_PAGE_TRANSMIT_MSG              0
#define MSK_PHYREG_NEXT_PAGE_TRANSMIT_MSG              0x07ff
#define SRT_PHYREG_NEXT_PAGE_TRASNMIT_TOGGLE           11
#define MSK_PHYREG_NEXT_PAGE_TRANSMIT_TOGGLE           0x0800
#define SRT_PHYREG_NEXT_PAGE_TRASNMIT_ACKNOWLEDGE2     12
#define MSK_PHYREG_NEXT_PAGE_TRANSMIT_ACKNOWLEDGE2     0x1000
#define SRT_PHYREG_NEXT_PAGE_TRASNMIT_MSG_PAGE         13
#define MSK_PHYREG_NEXT_PAGE_TRANSMIT_MSG_PAGE         0x2000
#define SRT_PHYREG_NEXT_PAGE_TRASNMIT_NEXT_PAGE        15
#define MSK_PHYREG_NEXT_PAGE_TRANSMIT_NEXT_PAGE        0x8000

#endif /* #ifndef __HAL_PHY_H */
