#ifndef ETHMAC_VERSION_H_
#define ETHMAC_VERSION_H_

#define ETHMAC_VERSION_MAJOR    6
#define ETHMAC_VERSION_MINOR    2
#define ETHMAC_VERSION_BUILD    0
#define ETHMAC_VERSION_REVISION 2

#endif /* ETHMAC_VERSION_H_ */
