
#ifndef __HW_IRQID_EXTERNAL_DPM0_H
#define __HW_IRQID_EXTERNAL_DPM0_H

typedef enum
{
  IRQID_EXTERNAL_DPM0_INTPHY_CFG_IRQ = 60,
  IRQID_EXTERNAL_DPM0_BOD = 59,
  IRQID_EXTERNAL_DPM0_CRYPT = 58,
  IRQID_EXTERNAL_DPM0_GPIO_COM = 57,
  IRQID_EXTERNAL_DPM0_ADC1_ARM = 56,
  IRQID_EXTERNAL_DPM0_ADC0_ARM = 55,
  IRQID_EXTERNAL_DPM0_ETH = 54,
  IRQID_EXTERNAL_DPM0_HIF_PIO_ARM = 53,
  IRQID_EXTERNAL_DPM0_SQI = 52,
  IRQID_EXTERNAL_DPM0_LVDS2MII1_COM = 51,
  IRQID_EXTERNAL_DPM0_LVDS2MII0_COM = 50,
  IRQID_EXTERNAL_DPM0_TRIGGER_LT = 49,
  IRQID_EXTERNAL_DPM0_MSYNC1 = 48,
  IRQID_EXTERNAL_DPM0_MSYNC0 = 47,
  IRQID_EXTERNAL_DPM0_COM1 = 46,
  IRQID_EXTERNAL_DPM0_COM0 = 45,
  IRQID_EXTERNAL_DPM0_NFIFO_ARM_COM = 44,
  IRQID_EXTERNAL_DPM0_WDG_XPIC_COM_ARM = 43,
  IRQID_EXTERNAL_DPM0_XPIC_DEBUG_COM = 42,
  IRQID_EXTERNAL_DPM0_ECC_COM_2BIT_ERROR = 41,
  IRQID_EXTERNAL_DPM0_ECC_COM_1BIT_ERROR = 40,
  IRQID_EXTERNAL_DPM0_I2C1_COM = 39,
  IRQID_EXTERNAL_DPM0_I2C0_COM = 38,
  IRQID_EXTERNAL_DPM0_UART_COM = 37,
  IRQID_EXTERNAL_DPM0_MCP_COM = 36,
  IRQID_EXTERNAL_DPM0_DMAC_COM = 35,
  IRQID_EXTERNAL_DPM0_WDG_COM = 34,
  IRQID_EXTERNAL_DPM0_TIMER_COM_SYSTIME_S = 33,
  IRQID_EXTERNAL_DPM0_ARM_TIMER = 32,
  IRQID_EXTERNAL_DPM0_HS_COM_HOST_HSC8TO15 = 16,
  IRQID_EXTERNAL_DPM0_HS_COM_HOST_HSC7 = 15,
  IRQID_EXTERNAL_DPM0_HS_COM_HOST_HSC6 = 14,
  IRQID_EXTERNAL_DPM0_HS_COM_HOST_HSC5 = 13,
  IRQID_EXTERNAL_DPM0_HS_COM_HOST_HSC4 = 12,
  IRQID_EXTERNAL_DPM0_HS_COM_HOST_HSC3 = 11,
  IRQID_EXTERNAL_DPM0_HS_COM_HOST_HSC2 = 10,
  IRQID_EXTERNAL_DPM0_HS_COM_HOST_HSC1 = 9,
  IRQID_EXTERNAL_DPM0_HS_COM_HOST_HSC0 = 8,
  IRQID_EXTERNAL_DPM0_DPM0_COM_FIRMWARE = 2,
  IRQID_EXTERNAL_DPM0_DPM0_COM_ERR = 1,
  IRQID_EXTERNAL_DPM0_DPM0_COM_SW = 0
} IRQID_EXTERNAL_DPM0_E;
#endif
