#ifndef ETH2PS_VERSION_H_
#define ETH2PS_VERSION_H_

#define ETH2PS_VERSION_MAJOR    6
#define ETH2PS_VERSION_MINOR    3
#define ETH2PS_VERSION_BUILD    0
#define ETH2PS_VERSION_REVISION 0

#endif /* ETH2PS_VERSION_H_ */
