#ifndef __HAL_RAP_PORTCTRL_H
#define __HAL_RAP_PORTCTRL_H

#include <stdint.h>   /* ISO C: uint8_t/uint16_t/uint32_t definitions */
#include <stdbool.h>  /* ISO C: "bool" definition */

/*****************************************************************************/
/* Definitions                                                               */
/*****************************************************************************/

#define SRT_RAP_PORTCTRL_CFG_PORT         16
#define SRT_RAP_PORTCTRL_CFG_SEL          12
#define SRT_RAP_PORTCTRL_CFG_CTL           8
#define SRT_RAP_PORTCTRL_CFG_DRV           4
#define SRT_RAP_PORTCTRL_CFG_UDC           0
#define MSK_RAP_PORTCTRL_CFG_VAL  0x0000ffff

#define RAP_PORTCTRL_CFG_PORT_CNT      0x123 // todo: anpassen eventuell sizeof PORT_CONTROL structure???

/* port: port id, e.g. RAP_PORTCTRL_PORT_P0_0
 * sel: 0..3: REE MUX 0..3 according to pinning table
 * drv: driver strength, e.g. RAP_PORT_CTRL_CMOSIO_DRV_4MA
 * udc: pull resistor, e.g. RAP_PORT_CTRL_CMOSIO_UDC_PU50K
 */
#define RAP_PORTCTRL_CFG(port, sel, ctl, drv, udc) (port << 16)\
  |(sel << SRT_RAP_PORTCTRL_CFG_SEL)\
  |(ctl << SRT_RAP_PORTCTRL_CFG_CTL)\
  |(drv << SRT_RAP_PORTCTRL_CFG_DRV)\
  |(udc << SRT_RAP_PORTCTRL_CFG_UDC)

typedef enum
{
  RAP_PORTCTRL_PORT_P0_0 = 0x00, /* RDY_N */
  RAP_PORTCTRL_PORT_P0_1,        /* RUN_N */
  RAP_PORTCTRL_PORT_P0_2,        /* RST_OUT_N */

  RAP_PORTCTRL_PORT_P1_0 = 0x10,
  RAP_PORTCTRL_PORT_P1_1,
  RAP_PORTCTRL_PORT_P1_2,
  RAP_PORTCTRL_PORT_P1_3,
  RAP_PORTCTRL_PORT_P1_4,
  RAP_PORTCTRL_PORT_P1_5,

  RAP_PORTCTRL_PORT_P2_0 = 0x20,
  RAP_PORTCTRL_PORT_P2_1,

  RAP_PORTCTRL_PORT_P3_1 = 0x31,
  RAP_PORTCTRL_PORT_P3_2,
  RAP_PORTCTRL_PORT_P3_3,
  RAP_PORTCTRL_PORT_P3_4,
  RAP_PORTCTRL_PORT_P3_5,
  RAP_PORTCTRL_PORT_P3_6,
  RAP_PORTCTRL_PORT_P3_7,
  RAP_PORTCTRL_PORT_P3_8,
  RAP_PORTCTRL_PORT_P3_9,
  RAP_PORTCTRL_PORT_P3_10,
  RAP_PORTCTRL_PORT_P3_11,
  RAP_PORTCTRL_PORT_P3_12,
  RAP_PORTCTRL_PORT_P3_13,
  RAP_PORTCTRL_PORT_P3_14,
  RAP_PORTCTRL_PORT_P3_15,

  RAP_PORTCTRL_PORT_P4_0 = 0x40,
  RAP_PORTCTRL_PORT_P4_1,
  RAP_PORTCTRL_PORT_P4_2,
  RAP_PORTCTRL_PORT_P4_3,
  RAP_PORTCTRL_PORT_P4_4,
  RAP_PORTCTRL_PORT_P4_5,
  RAP_PORTCTRL_PORT_P4_6,
  RAP_PORTCTRL_PORT_P4_7,
  RAP_PORTCTRL_PORT_P4_8,
  RAP_PORTCTRL_PORT_P4_9,
  RAP_PORTCTRL_PORT_P4_10,
  RAP_PORTCTRL_PORT_P4_11,
  RAP_PORTCTRL_PORT_P4_12,
  RAP_PORTCTRL_PORT_P4_13,
  RAP_PORTCTRL_PORT_P4_14,
  RAP_PORTCTRL_PORT_P4_15,

  RAP_PORTCTRL_PORT_P5_0 = 0x50,
  RAP_PORTCTRL_PORT_P5_1,
  RAP_PORTCTRL_PORT_P5_2,
  RAP_PORTCTRL_PORT_P5_3,
  RAP_PORTCTRL_PORT_P5_4,
  RAP_PORTCTRL_PORT_P5_5,
  RAP_PORTCTRL_PORT_P5_6,
  RAP_PORTCTRL_PORT_P5_7,
  RAP_PORTCTRL_PORT_P5_8,
  RAP_PORTCTRL_PORT_P5_9,
  RAP_PORTCTRL_PORT_P5_10,
  RAP_PORTCTRL_PORT_P5_11,
  RAP_PORTCTRL_PORT_P5_12,
  RAP_PORTCTRL_PORT_P5_13,
  RAP_PORTCTRL_PORT_P5_14,
  RAP_PORTCTRL_PORT_P5_15,

  RAP_PORTCTRL_PORT_P6_0 = 0x60,
  RAP_PORTCTRL_PORT_P6_1,
  RAP_PORTCTRL_PORT_P6_2,
  RAP_PORTCTRL_PORT_P6_3,
  RAP_PORTCTRL_PORT_P6_4,
  RAP_PORTCTRL_PORT_P6_5,
  RAP_PORTCTRL_PORT_P6_6,
  RAP_PORTCTRL_PORT_P6_7,
  RAP_PORTCTRL_PORT_P6_8,
  RAP_PORTCTRL_PORT_P6_9,
  RAP_PORTCTRL_PORT_P6_10,
  RAP_PORTCTRL_PORT_P6_11,
  RAP_PORTCTRL_PORT_P6_12,
  RAP_PORTCTRL_PORT_P6_13,
  RAP_PORTCTRL_PORT_P6_14,
  RAP_PORTCTRL_PORT_P6_15,

  RAP_PORTCTRL_PORT_P7_0 = 0x70,
  RAP_PORTCTRL_PORT_P7_1,
  RAP_PORTCTRL_PORT_P7_2,
  RAP_PORTCTRL_PORT_P7_3,
  RAP_PORTCTRL_PORT_P7_4,
  RAP_PORTCTRL_PORT_P7_5,
  RAP_PORTCTRL_PORT_P7_6,
  RAP_PORTCTRL_PORT_P7_7,
  RAP_PORTCTRL_PORT_P7_8,
  RAP_PORTCTRL_PORT_P7_9,
  RAP_PORTCTRL_PORT_P7_10,
  RAP_PORTCTRL_PORT_P7_11,
  RAP_PORTCTRL_PORT_P7_12,
  RAP_PORTCTRL_PORT_P7_13,
  RAP_PORTCTRL_PORT_P7_14,
  RAP_PORTCTRL_PORT_P7_15,

  RAP_PORTCTRL_PORT_P8_0 = 0x80,
  RAP_PORTCTRL_PORT_P8_1,
  RAP_PORTCTRL_PORT_P8_2,
  RAP_PORTCTRL_PORT_P8_3,
  RAP_PORTCTRL_PORT_P8_4,
  RAP_PORTCTRL_PORT_P8_5,
  RAP_PORTCTRL_PORT_P8_6,
  RAP_PORTCTRL_PORT_P8_7,
  RAP_PORTCTRL_PORT_P8_8,
  RAP_PORTCTRL_PORT_P8_9,
  RAP_PORTCTRL_PORT_P8_10,
  RAP_PORTCTRL_PORT_P8_11,
  RAP_PORTCTRL_PORT_P8_12,
  RAP_PORTCTRL_PORT_P8_13,
  RAP_PORTCTRL_PORT_P8_14,
  RAP_PORTCTRL_PORT_P8_15,

  RAP_PORTCTRL_PORT_P9_0 = 0x90,
  RAP_PORTCTRL_PORT_P9_1,
  RAP_PORTCTRL_PORT_P9_2,
  RAP_PORTCTRL_PORT_P9_3,
  RAP_PORTCTRL_PORT_P9_4,
  RAP_PORTCTRL_PORT_P9_5,
  RAP_PORTCTRL_PORT_P9_6,
  RAP_PORTCTRL_PORT_P9_7,
  RAP_PORTCTRL_PORT_P9_8,
  RAP_PORTCTRL_PORT_P9_9,
  RAP_PORTCTRL_PORT_P9_10,
  RAP_PORTCTRL_PORT_P9_11,
  RAP_PORTCTRL_PORT_P9_12,
  RAP_PORTCTRL_PORT_P9_13,
  RAP_PORTCTRL_PORT_P9_14,
  RAP_PORTCTRL_PORT_P9_15,

  RAP_PORTCTRL_PORT_P10_0 = 0xa0,
  RAP_PORTCTRL_PORT_P10_1,
  RAP_PORTCTRL_PORT_P10_2,
  RAP_PORTCTRL_PORT_P10_3,
  RAP_PORTCTRL_PORT_P10_4,
  RAP_PORTCTRL_PORT_P10_5,
  RAP_PORTCTRL_PORT_P10_6,
  RAP_PORTCTRL_PORT_P10_7,
  RAP_PORTCTRL_PORT_P10_8,
  RAP_PORTCTRL_PORT_P10_9,
  RAP_PORTCTRL_PORT_P10_10,

  RAP_PORTCTRL_PORT_P11_0 = 0xb0,
  RAP_PORTCTRL_PORT_P11_1,
  RAP_PORTCTRL_PORT_P11_2,
  RAP_PORTCTRL_PORT_P11_3,
  RAP_PORTCTRL_PORT_P11_4,
  RAP_PORTCTRL_PORT_P11_5,
  RAP_PORTCTRL_PORT_P11_6,
  RAP_PORTCTRL_PORT_P11_7,

  RAP_PORTCTRL_PORT_P12_0 = 0xc0,
  RAP_PORTCTRL_PORT_P12_1,
  RAP_PORTCTRL_PORT_P12_2,
  RAP_PORTCTRL_PORT_P12_3,
  RAP_PORTCTRL_PORT_P12_4,
  RAP_PORTCTRL_PORT_P12_5,
  RAP_PORTCTRL_PORT_P12_6,
  RAP_PORTCTRL_PORT_P12_7,
  RAP_PORTCTRL_PORT_P12_8,
  RAP_PORTCTRL_PORT_P12_9,
  RAP_PORTCTRL_PORT_P12_10,
  RAP_PORTCTRL_PORT_P12_11,
  RAP_PORTCTRL_PORT_P12_12,
  RAP_PORTCTRL_PORT_P12_13,
  RAP_PORTCTRL_PORT_P12_14,
  RAP_PORTCTRL_PORT_P12_15,

  RAP_PORTCTRL_PORT_P13_0 = 0xd0,
  RAP_PORTCTRL_PORT_P13_1,
  RAP_PORTCTRL_PORT_P13_2,
  RAP_PORTCTRL_PORT_P13_3,
  RAP_PORTCTRL_PORT_P13_4,
  RAP_PORTCTRL_PORT_P13_5,
  RAP_PORTCTRL_PORT_P13_6,
  RAP_PORTCTRL_PORT_P13_7,
  RAP_PORTCTRL_PORT_P13_8,
  RAP_PORTCTRL_PORT_P13_9,
  RAP_PORTCTRL_PORT_P13_10,
  RAP_PORTCTRL_PORT_P13_11,

  RAP_PORTCTRL_PORT_P14_0 = 0xe0,
  RAP_PORTCTRL_PORT_P14_1,

  RAP_PORTCTRL_PORT_P15_0 = 0xf0,
  RAP_PORTCTRL_PORT_P15_1,
  RAP_PORTCTRL_PORT_P15_2,
  RAP_PORTCTRL_PORT_P15_3,
  RAP_PORTCTRL_PORT_P15_4,
  RAP_PORTCTRL_PORT_P15_5,
  RAP_PORTCTRL_PORT_P15_6,
  RAP_PORTCTRL_PORT_P15_7,
  RAP_PORTCTRL_PORT_P15_8,
  RAP_PORTCTRL_PORT_P15_9,
  RAP_PORTCTRL_PORT_P15_10,
  RAP_PORTCTRL_PORT_P15_11,
  RAP_PORTCTRL_PORT_P15_12,
  RAP_PORTCTRL_PORT_P15_13,

  RAP_PORTCTRL_PORT_P16_0 = 0x100,
  RAP_PORTCTRL_PORT_P16_1,
  RAP_PORTCTRL_PORT_P16_2,
  RAP_PORTCTRL_PORT_P16_3,
  RAP_PORTCTRL_PORT_P16_4,
  RAP_PORTCTRL_PORT_P16_5,
  RAP_PORTCTRL_PORT_P16_6,
  RAP_PORTCTRL_PORT_P16_7,
  RAP_PORTCTRL_PORT_P16_8,
  RAP_PORTCTRL_PORT_P16_9,
  RAP_PORTCTRL_PORT_P16_10,
  RAP_PORTCTRL_PORT_P16_11,

  RAP_PORTCTRL_PORT_P17_0 = 0x110,
  RAP_PORTCTRL_PORT_P17_1, /* reserved for 2nd pin of P17_0 buffer */
  RAP_PORTCTRL_PORT_P17_2,
  RAP_PORTCTRL_PORT_P17_3, /* reserved for 2nd pin of P17_2 buffer */

  RAP_PORTCTRL_PORT_P18_0 = 0x120,
  RAP_PORTCTRL_PORT_P18_1, /* reserved for 2nd pin of P18_0 buffer */
  RAP_PORTCTRL_PORT_P18_2,
  RAP_PORTCTRL_PORT_P18_3 /* reserved for 2nd pin of P18_2 buffer */
} RAP_PORTCTRL_PORT_E;

typedef enum
{
  RAP_PORT_CTRL_CMOSIO_UDC_NONE  = 0,
  RAP_PORT_CTRL_CMOSIO_UDC_PU50K = 1,
  RAP_PORT_CTRL_CMOSIO_UDC_PD50K = 3
} RAP_PORT_CTRL_CMOSIO_UDC_E;

typedef enum
{
  RAP_PORT_CTRL_CMOSIO_DRV_4MA   = 0,
  RAP_PORT_CTRL_CMOSIO_DRV_6MA   = 1,
  RAP_PORT_CTRL_CMOSIO_DRV_8MA   = 2,
  RAP_PORT_CTRL_CMOSIO_DRV_12MA  = 3
} RAP_PORT_CTRL_CMOSIO_DRV_E;

typedef enum
{
  RAP_PORTCTRL_RESULT_OK = 0,
  RAP_PORTCTRL_RESULT_INVAL_PARAM
} RAP_PORTCTRL_RESULT_E;

/*****************************************************************************/
/* Function prototypes                                                       */
/*****************************************************************************/

RAP_PORTCTRL_RESULT_E RAP_PortCtrl_SetCfg ( const uint32_t* paulConfigTable, unsigned int uiNumEntries );
uint32_t              RAP_PortCtrl_GetCfg ( RAP_PORTCTRL_PORT_E ePort );

#endif /* __HAL_RAP_PORTCTRL_H */
