#ifndef __HAL_RAP_EDGE_IRQ_H
#define __HAL_RAP_EDGE_IRQ_H

typedef enum
{
	IRQID_RAP_EDGE_I_PCIE_ERR_COR_DETECTED = 0,
	IRQID_RAP_EDGE_I_PCIE_ERR_FATAL_DETECTED = 1,
	IRQID_RAP_EDGE_I_PCIE_ERR_NONFATAL_DETECTED = 2,
	IRQID_RAP_EDGE_I_IIS_0_IISATIFERR = 3,
	IRQID_RAP_EDGE_I_IIS_0_IISATIRXO = 4,
	IRQID_RAP_EDGE_I_IIS_0_IISATIRXT = 5,
	IRQID_RAP_EDGE_I_IIS_0_IISATITXT = 6,
	IRQID_RAP_EDGE_I_IIS_0_IISATITXU = 7,
	IRQID_RAP_EDGE_I_IIS_1_IISATIFERR = 8,
	IRQID_RAP_EDGE_I_IIS_1_IISATIRXO = 9,
	IRQID_RAP_EDGE_I_IIS_1_IISATIRXT = 10,
	IRQID_RAP_EDGE_I_IIS_1_IISATITXT = 11,
	IRQID_RAP_EDGE_I_IIS_1_IISATITXU = 12,
	IRQID_RAP_EDGE_I_IIS_2_IISATIFERR = 13,
	IRQID_RAP_EDGE_I_IIS_2_IISATIRXO = 14,
	IRQID_RAP_EDGE_I_IIS_2_IISATIRXT = 15,
	IRQID_RAP_EDGE_I_IIS_2_IISATITXT = 16,
	IRQID_RAP_EDGE_I_IIS_2_IISATITXU = 17,
	IRQID_RAP_EDGE_I_SIGMA_DELTA_IF_ERR_UVW_I = 18,
	IRQID_RAP_EDGE_I_SIGMA_DELTA_IF_ERR_UVW_IGND = 19,
	IRQID_RAP_EDGE_I_SIGMA_DELTA_IF_ERR_UVW_HZ = 20,
	IRQID_RAP_EDGE_I_SIGMA_DELTA_IF_ERR_XYZ_I = 21,
	IRQID_RAP_EDGE_I_SIGMA_DELTA_IF_ERR_XYZ_IGND = 22,
	IRQID_RAP_EDGE_I_SIGMA_DELTA_IF_ERR_XYZ_HZ = 23,
	IRQID_RAP_EDGE_I_RTC_RTCATINTAL = 24,
	IRQID_RAP_EDGE_I_RTC_RTCATINTR = 25,
	IRQID_RAP_EDGE_I_RTC_RTCATINT1S = 26
} RAP_EDGE_IRQ_E;
#endif


